app:
  name: "rag-mysql"
  debug: true

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "0765"
  database: "connec2"

groq:
  api_key: "${GROQ_API_KEY}"
  model: "llama-3.1-70b-versatile"

embedding_model:
  model_name: "text-embedding-004"

llm:
  openai:
    model_name: "gpt-4o-mini"
    temperature: 0.2
